version: '3'

services:

  gateway-service:
    build: ../gateway
    container_name: gateway-service
    ports:
      - '${GATE_WAY_PORT}:${GATE_WAY_PORT}'
    expose:
      - '${GATE_WAY_PORT}'
    networks:
      - app-network


  front-end:
    build: ../frontend
    container_name: frontend
    ports:
      - '${FRONT_END_PORT}:80'
    expose:
      - '${FRONT_END_PORT}'

	  

  appmanagementMs1-db:
    image: ${APPMANAGEMENTMS1_DB_IMAGE_NAME}
    container_name: ${APPMANAGEMENTMS1_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "${APPMANAGEMENTMS1_DB_PORT}:${APPMANAGEMENTMS1_DB_PORT}"
    environment:
      - MYSQL_DATABASE=${APPMANAGEMENTMS1_DB_NAME}
      - MYSQL_USER=${APPMANAGEMENTMS1_DB_USER}
      - MYSQL_PASSWORD=${APPMANAGEMENTMS1_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${APPMANAGEMENTMS1_DB_PASSWORD_ROOT}
    networks:
      - app-network

  appmanagementMs1-back:
    build: ${APPMANAGEMENTMS1_PROJECT_PATH}
    container_name: ${APPMANAGEMENTMS1_CONTAINER_NAME}
    image: ${APPMANAGEMENTMS1_IMAGE_NAME}
    ports:
      - "${APPMANAGEMENTMS1_BACK_PORT}:${APPMANAGEMENTMS1_BACK_PORT}"
    environment:
      - APPMANAGEMENTMS1_DB_URL=${APPMANAGEMENTMS1_DB_URL}
      - APPMANAGEMENTMS1_DB_USER=${APPMANAGEMENTMS1_DB_USER}
      - APPMANAGEMENTMS1_DB_PASSWORD=${APPMANAGEMENTMS1_DB_PASSWORD}
    depends_on:
      - appmanagementMs1-db
    networks:
      - app-network


  minio:
    image: ${MINIO_IMAGE_NAME}
    container_name: ${MINIO_CONTAINER_NAME}
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio_data:/data
    ports:
      - "${MINIO_HOME_PORT}:9000"
      - "${MINIO_URL_PORT}:9001" # tap localhost:9001 to access to minio
    networks:
      - app-network


volumes:
  app-data:

networks:
  app-network:
    external: true
